DROP TABLE IF EXISTS STUDENTS, FACULTIES;

CREATE TABLE FACULTIES
(
    ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(256)
);

CREATE TABLE STUDENTS
(
    ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIO VARCHAR(256),
    FACULTY_ID BIGINT
);

ALTER TABLE STUDENTS ADD FOREIGN KEY (FACULTY_ID) REFERENCES FACULTIES(ID)